export * from './comment.dto';
export * from './course.dto';
export * from './course.request.dto';
export * from './education.dto';
export * from './notification.dto';
export * from './professor.dto';
export * from './scoring.dto';
export * from './student.dto';
export * from './user.abstract.dto';
