export * from './comment.entity';
export * from './course.entity';
export * from './course.request.entity';
export * from './education.entity';
export * from './notification.entity';
export * from './professor.entity';
export * from './scoring.entity';
export * from './student.entity';
export * from './user.abstract.entity';
